# Generated by Django 4.2 on 2023-05-11 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0002_product_category_alter_product_discount_parcent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='highlight',
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='FK_product_sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userModule.product_subcategory'),
        ),
    ]
