# Generated by Django 4.2 on 2023-05-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0003_remove_product_highlight_product_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_category',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
