# Generated by Django 4.2 on 2023-05-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0004_alter_product_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_parcent',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
    ]
