# Generated by Django 4.2 on 2023-05-11 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0005_alter_product_discount_parcent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('FK_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userModule.product')),
            ],
        ),
    ]
