# Generated by Django 4.2 on 2023-05-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0009_alter_usermodel_ph_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_subcategory',
            name='subCat_image',
            field=models.ImageField(blank=True, null=True, upload_to='Prod_subCat_Img/'),
        ),
    ]
