# Generated by Django 4.2 on 2023-05-14 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0010_product_subcategory_subcat_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='default_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product_subcategory',
            old_name='subCat_image',
            new_name='image',
        ),
    ]
