# Generated by Django 4.2 on 2023-05-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0011_rename_default_image_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feature_summary',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
