# Generated by Django 4.2 on 2023-05-17 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0012_product_feature_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_category',
            old_name='product_type',
            new_name='cat_name',
        ),
        migrations.RenameField(
            model_name='product_subcategory',
            old_name='product_sub_category',
            new_name='subCat_name',
        ),
        migrations.CreateModel(
            name='subcat_type',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=250)),
                ('FK_product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userModule.product_category')),
            ],
        ),
        migrations.AddField(
            model_name='product_subcategory',
            name='FK_subcat_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userModule.subcat_type'),
        ),
    ]
