# Generated by Django 4.2 on 2023-05-17 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0013_rename_product_type_product_category_cat_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_subcategory',
            name='FK_product_category',
        ),
    ]
