# Generated by Django 4.2 on 2023-05-17 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0014_remove_product_subcategory_fk_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_subcategory',
            name='FK_product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userModule.product_category'),
        ),
    ]
