# Generated by Django 4.2 on 2023-05-18 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0015_product_subcategory_fk_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
