# Generated by Django 4.2 on 2023-05-18 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0016_remove_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='features',
            new_name='description',
        ),
    ]
