# Generated by Django 4.2 on 2023-05-18 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0017_rename_features_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='feature_summary',
            new_name='description_summary',
        ),
    ]
