# Generated by Django 4.2 on 2023-05-22 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0018_rename_feature_summary_product_description_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('transection_id', models.CharField(max_length=255)),
                ('order_staus', models.CharField(choices=[('panding', 'panding'), ('order confirmed', 'order confirmed'), ('ready to dispatch', 'ready to dispatch'), ('out for delivery', 'out for delivery'), ('delivered', 'delivered'), ('cancellation', (('out for pickup', 'out for pickup'), ('cancelled', 'cancelled')))], default='panding', max_length=50)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('FK_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userModule.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
