# Generated by Django 4.2 on 2023-05-31 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0020_user_address_order_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
